### ISSUE TITLE
Support separate /var

### ISSUE THREAD

**Issue by cgwalters** [coreos/ignition-dracut#18] opened 2018-09-19 12:27 UTC
https://github.com/dustymabe/ignition-dracut/pull/7

**Comment by dustymabe** [comment] 2018-09-19 12:51
so I think the ask is specifically to address this:

https://github.com/dustymabe/ignition-dracut/blob/d056287951bd6823d6c087a81b63c9eb271ab240/dracut/30ignition/ignition-ask-var-mount.service#L1-L5

**Comment by dustymabe** [comment] 2018-09-19 14:02
is `/var/` the only concern we have here. are there other filesystems users may want to set up in ignition-disks and populate files in using ignition? 

cc @lucab

**Comment by dustymabe** [comment] 2018-09-19 14:17
>  are there other filesystems users may want to set up in ignition-disks and populate files in using ignition?

it looks like maybe ignition-disks already handles that for us

**Comment by lucab** [comment] 2018-09-19 16:07
I'm sorry this ticket is a bit too terse in details, so I may be missing the point.

If you are asking about "creating additional partitions, formatting them, writing files to them, and mounting them in the real rootfs", this is how it currently works in CL:
 * "creating additional partitions" -> `storage.disks` stanza, handled by `ignition-disks`
 * "formatting" -> `storage.filesystems` stanza, handled by `ignition-disks`
 * "writing files" -> `storage.files` stanza, handled by `ignition-files` (temporary mount/umount done internally)
 * "mounting in the real rootfs" -> this is done by the user via a mount unit: https://coreos.com/os/docs/latest/mounting-storage.html

**Comment by dustymabe** [comment] 2018-09-19 18:49
ok so I think ignition-disks already handles any filesystems the user requests (via ignition) so we only need to worry about mounting var.

**Comment by jlebon** [comment] 2018-10-02 14:13
Was chatting about this with @lucab. So right now, `/var` is mounted post-pivot either by the fstab generator fishing it out of `/etc/fstab`, or an OSTree generator which notices that it's *not* in fstab and creating a `var.mount` bind mount from `/ostree/deploy/$stateroot/var`.

@lucab mentioned that there's an [x-initrd.mount](https://www.freedesktop.org/software/systemd/man/systemd.mount.html#x-initrd.mount) we could make use of so that it instead gets mounted in the initramfs. (And then `ignition-files` can drop files in there.)  That would mean though that `ostree-prepare-root.service` would need to run *before* the var mount. To keep it consistent, we'd also want to do the bind mount in the case when there isn't a `/var` partition around that same time. So timing overall could be tricky to get right.

Alternatively, just replace the `ignition-ask-var-mount.service` approach with a smarter `ostree-prepare-root` that can look for `/var` in `/sysroot/etc/fstab`? And if not, do the bind mount as it does currently. (All of this still gated behind `/run/ostree/initramfs-mount-var` of course).

**Comment by jlebon** [comment] 2018-10-02 14:19
> @lucab mentioned that there's an x-initrd.mount we could make use of so that it instead gets mounted in the initramfs

IIUC for this approach to work right, we'd have to tweak Anaconda/whatever writes `/etc/fstab` to point the mountpoint at `/sysroot/var` instead of `/var`, right?

**Comment by lucab** [comment] 2018-10-02 14:35
@jlebon if I remember correctly, systemd already takes care of that (i.e. `/sysroot` prepending and more) when in initramfs-mode it consumes real-rootfs unit files.

@dustymabe if you are speaking about partition detection, we usually try to make that automatically discoverable via GPT bits (e.g. partition labels, well-known types, metadata, IDs) that can be touched by Ignition. I don't have a specific suggestion here, but we can follow a similar approach.

**Comment by thkukuk** [comment] 2018-10-17 08:41
I have no idea about the requirements for OSTree, but at SUSE we had a similar problem with our read-only root filesystem implementation. The solution was, that we create a fstab.sys which mounts the additional partitions we need. So for /var it looks like:
# cat /etc/fstab.sys 
UUID=72e8845a-212f-4ab6-b732-854f4298324f  /var                    btrfs  subvol=/@/var                 0  0

Easy enhanceable to /home and other partitions we maybe need to mount.

**Comment by ajeddeloh** [comment] 2018-10-18 20:13
Really the problem isn't `/var`; it's `/var/home` and `/var/root`*. The files stages handles:
1) systemd units (needs `/etc` available, currently specified via the `-root` param)
2) users and groups (needs `/home` (or wherever a link would resolve to) and `/etc`)
3) files/links/dirs (doesn't actually need anything since it knows how to mount it)

For our cases `/etc` needs to be on the rootfs, so that's taken care of by `-root` and we don't need to worry about it. It would be bad to mount `/var` without Ignition knowing about it in case a user wants to reformat then write files to it, but we also need it mounted for resolving users for the files stage. I'm not really sure what the best path forward is. Maybe have Ignition resolve all user/group names to uids/gids after the passwd section is done?

* assuming users aren't creating home directories for users elsewhere. We could just not support creating it outside of mounted devices.

**Comment by ajeddeloh** [comment] 2018-11-27 23:38
Wrote up a proposal for how to handle this with spec 3.0.0 here: https://github.com/coreos/ignition/issues/669

**Comment by jlebon** [comment] 2019-04-30 20:01
This is fixed now.

**Closed by jlebon** 2019-04-30 20:01 UTC
